Fix for running in Rails 7 + Ruby 3
When previewing an email I get the following stack track:

```
NoMethodError (undefined method `exception' for nil:NilClass

        reason.exception(*args)
              ^^^^^^^^^^):

concurrent-ruby (1.1.9) lib/concurrent-ruby/concurrent/concern/obligation.rb:128:in `exception'
concurrent-ruby (1.1.9) lib/concurrent-ruby/concurrent/concern/obligation.rb:87:in `raise'
concurrent-ruby (1.1.9) lib/concurrent-ruby/concurrent/concern/obligation.rb:87:in `block in wait!'
<internal:kernel>:90:in `tap'
concurrent-ruby (1.1.9) lib/concurrent-ruby/concurrent/concern/obligation.rb:87:in `wait!'
sprockets (4.0.2) lib/sprockets/manifest.rb:130:in `each'
sprockets (4.0.2) lib/sprockets/manifest.rb:130:in `find'
sprockets (4.0.2) lib/sprockets/manifest.rb:142:in `each'
sprockets (4.0.2) lib/sprockets/manifest.rb:142:in `find_sources'
premailer-rails (1.11.1) lib/premailer/rails/css_loaders/asset_pipeline_loader.rb:11:in `each'
```

Not sure what is causing this issue, but collection the enumerator to an
Array before getting the first item seems to fix it.